version: 2
jobs:
  build-job:
    docker:
      - image: blang/latex
    steps:
      - checkout
      - run:
          name: Build paper
          command: pdflatex main.tex && bibtex main && pdflatex main.tex && pdflatex main.tex
      - run:
          name: Make workspace
          command: mkdir -p /tmp/workspace
      - run:
          name: Copy whitepaper to workspace
          command: cp ./main.pdf /tmp/workspace/whitepaper.pdf
      - run:
          name: Copy deploy script to workspace
          command: cp ./deploy.sh /tmp/workspace/deploy.sh
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - whitepaper.pdf
            - deploy.sh

  deploy-job:
    docker:
      - image: blang/latex
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install Curl
          command: apt-get update && apt-get install curl -y
      - run:
          name: Install lsb_release
          command: apt-get install lsb-release -y
      - run:
          name: Install Gcloud
          command: CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && apt-get update && apt-get install google-cloud-sdk -y
      - run:
          name: Install kubectl
          command: apt-get install kubectl
      - run:
          name: Deploy (should only be running if tests passed and branch is master)
          command: bash /tmp/workspace/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          # filters:
          #   branches:
          #     only: master
