version: 2
jobs:
  build:
    docker:
      - image: blang/latex
    steps:
      - checkout
      - run:
          name: Build paper
          command: pdflatex main.tex && bibtex main && pdflatex main.tex && pdflatex main.tex
      # - run:
          # name: Print the Current Time
          # command: date
